version: "3.8"

services:
  server:
    image: "${DOCKER_CONTAINER_REGISTRY}/backend:${GITHUB_SHA}"
    container_name: onku
    environment:
      TZ: Asia/Seoul
    ports:
      - '8080:8080'
    depends_on:
      - redis
    networks:
      - onku-network
  redis:
    image: redis:6.0.9
    container_name: onku-redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - onku-network

volumes:
  redis-data:

networks:
  onku-network:
    driver: bridge